version: '3.9'
services:
  server:
    container_name: server
    build: .
    volumes:
      - .:/app
      - static:/app/static
      - media:/app/media
    env_file:
      - .env
    environment:
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx-conf.d:/etc/nginx/conf.d
      - static:/app/static
      - media:/app/media
    depends_on:
      - server
    restart: unless-stopped

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    depends_on:
      - server
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
      - static:/app/static
      - media:/app/media
    ports:
      - "4040:4040"

volumes:
  static:
  media:
  postgres_data:

