class State:
    NONE_STATE = ''

    ENTER_TWO_AUTH_CODE = 'ENTER_TWO_AUTH_CODE'

    WRITE_SUPPORT_TITLE = 'WRITE_SUPPORT_TITLE'
    WRITE_SUPPORT_DESCRIPTION = 'WRITE_SUPPORT_DESCRIPTION'
    WRITE_SUPPORT_ENTER_TWO_AUTH_CODE = 'WRITE_SUPPORT_ENTER_TWO_AUTH_CODE'
