class State:
    NONE_STATE = ''

    ENTER_TWO_AUTH_CODE = 'ENTER_TWO_AUTH_CODE'

    WRITE_SUPPORT_TITLE = 'WRITE_SUPPORT_TITLE'
    WRITE_SUPPORT_DESCRIPTION = 'WRITE_SUPPORT_DESCRIPTION'
    WRITE_SUPPORT_ENTER_TWO_AUTH_CODE = 'WRITE_SUPPORT_ENTER_TWO_AUTH_CODE'

    SET_SCHEDULE_DATE = 'SET_SCHEDULE_DATE'
    SET_SCHEDULE_TIME = 'SET_SCHEDULE_TIME'
    SET_SCHEDULE_TEXT = 'SET_SCHEDULE_TEXT'
