# Generated by Django 5.0.1 on 2024-02-19 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_support', '0001_initial'),
        ('user', '0007_telegramuser_two_auth_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.telegramuser'),
        ),
    ]
