# Generated by Django 5.0.1 on 2024-02-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_telegramuser_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='two_auth_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
